name: Check code health

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --enable-all

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup project
        run: make setup

      - name: Run tests
        run: |
          make run &
          sleep 10
          make test

  Vulnerability:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
